export enum CallType {
  UNKNOWN = 0,
  VOICE,
  VIDEO,
}

export enum CallStatus {
  UNKNOWN = 0,
  CANCELED, // caller cancel
  REJECTED, // callee reject
  MISSED,
  ONGOING,
  ENDED,
}

export interface CallRecordPayload {
  starter: string,
  participants: string[],
  length: number, // in seconds
  type: CallType,
  status: CallStatus,
}

/**
 * Call media type for the signaling domain.
 * String values are used for JSON payload debugging friendliness.
 */
export enum CallMediaType {
  Audio = 'audio',
  Video = 'video',
}

/**
 * Call control signal driving call state machine transitions.
 */
export enum CallSignal {
  Invite  = 'invite',   // caller initiates
  Ringing = 'ringing',  // callee is ringing (acknowledgement)
  Accept  = 'accept',   // callee accepts
  Reject  = 'reject',   // callee rejects
  Cancel  = 'cancel',   // caller cancels before the call is connected
  Hangup  = 'hangup',   // either side hangs up after connected
}

/**
 * Downlink control command payload: local side → remote side.
 */
export interface CallControlPayload {
  callId  : string         // unique call id (generated by caller, propagated end-to-end)
  signal  : CallSignal
  peerId  : string         // contactId of the controlled party
  media?  : CallMediaType  // required when signal === Invite
  reason? : string         // optional when signal === Reject or Hangup
}
