import type { FileBoxInterface } from 'file-box'

/**
 * Email schema.
 *
 * EmailPayload is used for BOTH receive and send.
 *
 * On send, the following fields are generated by the protocol side and any
 * caller-supplied value is ignored:
 *   - from          : the sending mailbox is the logged-in identity
 *   - date          : stamped when the protocol side dispatches the mail
 *   - mimeMessageId : the RFC 5322 Message-ID is assigned by the mail server
 * inReplyTo (and references) should be set by the caller to thread a reply
 * onto an existing conversation.
 */

export interface EmailAddress {
  address : string,   // email address, same shape as the email-channel contact id
  name?   : string,   // display name, e.g. "Zhao Si"
}

export interface EmailAttachment {
  filename     : string,
  contentType? : string,             // always present on receive; optional on send (derived from extension)
  size?        : number,             // bytes; always present on receive
  inline?      : boolean,            // true = inline resource referenced by html via cid:
  cid?         : string,             // Content-ID anchor for cid: references in html
  url?         : string,             // RECEIVE ONLY: public URL after the attachment lands on object storage, for direct display/download; messageFile(messageId, index) stays as the fallback fetch path
  fileBox?     : FileBoxInterface,   // SEND ONLY: attachment content; never set on receive — fetch via messageFile(messageId, index)
}

export interface EmailPayload {
  subject        : string,
  from           : EmailAddress,
  to             : EmailAddress[],
  cc?            : EmailAddress[],
  bcc?           : EmailAddress[],
  date?          : number,             // Date header in ms; distinct from message timestamp (fetch time)
  mimeMessageId? : string,             // RFC 5322 Message-ID, threading anchor / dedup key
  inReplyTo?     : string,
  references?    : string[],
  replyTo?       : EmailAddress[],              // Reply-To: reply target, takes precedence over `from`
  sender?        : EmailAddress,                // Sender: actual submitter when From is multiple/delegated
  headers?       : { [name: string]: string },  // escape hatch: unmapped raw headers passed through on demand
  text?          : string,             // plain-text body (may be downgraded from html)
  html?          : string,             // sanitized html body (the authoritative rendition)
  attachments?   : EmailAttachment[],
}
