import type {
  ContactPayload,
  EventDirtyPayload,
  EventDongPayload,
  EventErrorPayload,
  EventFriendshipPayload,
  EventHeartbeatPayload,
  EventLoginPayload,
  EventLogoutPayload,
  EventMessagePayload,
  EventReadyPayload,
  EventResetPayload,
  EventRoomInvitePayload,
  EventRoomJoinPayload,
  EventRoomLeavePayload,
  EventRoomTopicPayload,
  EventRoomAnnouncePayload,
  EventScanPayload,
  EventTagPayload,
  EventTagGroupPayload,
  EventPostPayload,
  EventPostCommentPayload,
  EventPostTapPayload,

  FriendshipPayload,
  FriendshipPayloadConfirm,
  FriendshipPayloadReceive,
  FriendshipPayloadVerify,
  LocationPayload,
  MessagePayload,
  MessagePayloadBase,
  MessagePayloadRoom,
  MessagePayloadTo,
  MiniProgramPayload,
  PostPayload,
  PostPayloadClient,
  PostPayloadServer,
  RoomInvitationPayload,
  RoomMemberPayload,
  RoomPayload,
  TapPayload,
  UrlLinkPayload,
  SayablePayload,
  ChannelPayload,
  ChannelCardPayload,
  ConsultCardPayload,
  ConsultCardAction,
  PremiumOnlineAppointmentCardPayload,
  IMComponent,
  TagGroupPayload,
  TagPayload,
  EventVerifyCodePayload,
  EventVerifySlidePayload,
  EventLoginUrlPayload,
  CallRecordPayload,
  ChatHistoryPayload,
  IntentCommentPayload,
  EventIntentCommentPayload,
  EventContactEnterConversationPayload,
  EventContactLeadFilledPayload,
  EventWxxdProductPayload,
  EventWxxdOrderPayload,
  WxxdShopPayload,
  WxxdProductPayload,
  WxxdProductExtraServicePayload,
  WxxdProductDescInfoPayload,
  WxxdProductSkuPayload,
  WxxdOrderSkuAttrPayload,
  WxxdOrderExtInfoPayload,
  WxxdOrderProductPayload,
  WxxdOrderPayload,
}                           from '../schemas/mod.js'
import {
  sayablePayloads,
  isPostPayloadServer,
  isPostPayloadClient,
}                           from '../schemas/mod.js'

export type {
  ContactPayload                          as Contact,
  EventDirtyPayload                       as EventDirty,
  EventDongPayload                        as EventDong,
  EventErrorPayload                       as EventError,
  EventFriendshipPayload                  as EventFriendship,
  EventHeartbeatPayload                   as EventHeartbeat,
  EventLoginPayload                       as EventLogin,
  EventLogoutPayload                      as EventLogout,
  EventMessagePayload                     as EventMessage,
  EventPostPayload                        as EventPost,
  EventPostCommentPayload                 as EventPostComment,
  EventPostTapPayload                     as EventPostTap,
  EventReadyPayload                       as EventReady,
  EventResetPayload                       as EventReset,
  EventRoomInvitePayload                  as EventRoomInvite,
  EventRoomJoinPayload                    as EventRoomJoin,
  EventRoomLeavePayload                   as EventRoomLeave,
  EventRoomTopicPayload                   as EventRoomTopic,
  EventRoomAnnouncePayload                as EventRoomAnnounce,
  EventScanPayload                        as EventScan,
  EventTagPayload                         as EventTag,
  EventTagGroupPayload                    as EventTagGroup,
  EventVerifyCodePayload                  as EventVerifyCode,
  EventVerifySlidePayload                 as EventVerifySlide,
  EventLoginUrlPayload                    as EventLoginUrl,
  EventIntentCommentPayload               as EventIntentComment,
  EventContactEnterConversationPayload    as EventContactEnterConversation,
  EventContactLeadFilledPayload           as EventContactLeadFilled,
  FriendshipPayload                       as Friendship,
  FriendshipPayloadConfirm                as FriendshipConfirm,
  FriendshipPayloadReceive                as FriendshipReceive,
  FriendshipPayloadVerify                 as FriendshipVerify,
  LocationPayload                         as Location,
  MessagePayload                          as Message,
  MessagePayloadBase                      as MessageBase,
  MessagePayloadRoom                      as MessageRoom,
  MessagePayloadTo                        as MessageTo,
  MiniProgramPayload                      as MiniProgram,
  PostPayload                             as Post,
  PostPayloadClient                       as PostClient,
  PostPayloadServer                       as PostServer,
  RoomInvitationPayload                   as RoomInvitation,
  RoomMemberPayload                       as RoomMember,
  RoomPayload                             as Room,
  SayablePayload                          as Sayable,
  TapPayload                              as Tap,
  UrlLinkPayload                          as UrlLink,
  ChannelPayload                          as Channel,
  ChannelCardPayload                      as ChannelCard,
  TagGroupPayload                         as TagGroup,
  TagPayload                              as Tag,
  CallRecordPayload                       as CallRecord,
  ChatHistoryPayload                      as ChatHistory,
  ConsultCardPayload                      as ConsultCard,
  PremiumOnlineAppointmentCardPayload     as PremiumOnlineAppointmentCard,
  IntentCommentPayload                    as IntentComment,
  WxxdShopPayload                          as WxxdShop,
  WxxdProductPayload                       as WxxdProduct,
  WxxdProductExtraServicePayload           as WxxdProductExtraService,
  WxxdProductDescInfoPayload               as WxxdProductDescInfo,
  WxxdProductSkuPayload                    as WxxdProductSku,
  WxxdOrderSkuAttrPayload                  as WxxdOrderSkuAttr,
  WxxdOrderExtInfoPayload                  as WxxdOrderExtInfo,
  WxxdOrderProductPayload                  as WxxdOrderProduct,
  WxxdOrderPayload                         as WxxdOrder,
  ConsultCardAction,
  IMComponent,
}
export {
  sayablePayloads as sayable, // Sayable payload creators
  isPostPayloadServer as isPostServer,
  isPostPayloadClient as isPostClient,
}
