import {
  log,
} from '../config.js'

import type { PuppetSkeleton } from '../puppet/puppet-skeleton.js'
import type { CallMediaType } from '../schemas/call.js'

/**
 * Explicit return type annotation truncates the TypeScript instantiation depth
 * for the callers (puppet-abstract.ts validateMixin chain) that otherwise trigger TS2589.
 */
type CallMixinReturn<MixinBase extends typeof PuppetSkeleton> =
  MixinBase & (abstract new (...args: any[]) => {
    callInvite(contactIds: string[], media: CallMediaType): Promise<string>,
    callAdd(callId: string, contactIds: string[]): Promise<void>,
    callAccept(callId: string): Promise<void>,
    callReject(callId: string, reason?: string): Promise<void>,
    callCancel(callId: string): Promise<void>,
    callHangup(callId: string, reason?: string): Promise<void>,
  })

const callMixin = <MixinBase extends typeof PuppetSkeleton>(mixinBase: MixinBase): CallMixinReturn<MixinBase> => {

  abstract class CallMixin extends mixinBase {

    constructor (...args: any[]) {
      super(...args)
      log.verbose('PuppetCallMixin', 'constructor()')
    }

    /**
     * Initiate an outbound call to one or more contacts.
     *
     * A single-element array starts a 1v1 call; multiple elements start a
     * group call. Either way, one call mints exactly one callId, which is
     * generated by the puppet implementation (the protocol side), not by the
     * caller. The remote parties' responses — including events that may arrive
     * before this Promise resolves — are delivered uplink through the 'call'
     * event.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callInvite (contactIds: string[], media: CallMediaType): Promise<string>

    /**
     * Add contacts to an existing call (callAdd is to callInvite what
     * roomAddV2 is to roomCreate).
     *
     * Errors-only semantics: a resolved Promise only means the add request
     * has been accepted by the protocol side. The new participants' business
     * responses (ringing / accept / reject) are delivered uplink through the
     * 'call' event — EventCallPayload.contactId is the new participant (the
     * actor of that signal), and EventCallPayload.participants may carry the
     * updated roster. Add-specific failures (call not found / already ended,
     * participant cap exceeded) are expressed via Promise rejection.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callAdd (callId: string, contactIds: string[]): Promise<void>

    /**
     * Accept an incoming call.
     *
     * Only meaningful for an incoming call. The protocol side locates the
     * call session by callId (from the incoming-call event).
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callAccept (callId: string): Promise<void>

    /**
     * Reject an incoming call.
     *
     * Only meaningful for an incoming call. The protocol side locates the
     * call session by callId (from the incoming-call event).
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callReject (callId: string, reason?: string): Promise<void>

    /**
     * Cancel an outbound call before it is connected.
     *
     * Only meaningful for an outbound call that has not been connected yet.
     * The protocol side locates the call session by callId (from callInvite()).
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callCancel (callId: string): Promise<void>

    /**
     * Hang up a connected call.
     *
     * Only meaningful for a call that is already connected. The protocol side
     * locates the call session by callId.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callHangup (callId: string, reason?: string): Promise<void>

  }

  return CallMixin as unknown as CallMixinReturn<MixinBase>
}

type CallMixin = ReturnType<typeof callMixin>
type ProtectedPropertyCallMixin = never

export type {
  CallMixin,
  ProtectedPropertyCallMixin,
}
export { callMixin }
