import {
  log,
} from '../config.js'

import type { PuppetSkeleton } from '../puppet/puppet-skeleton.js'
import type { CallMediaEndpointPayload, CallMediaType, CallPayload } from '../schemas/call.js'
import { DirtyType } from '../schemas/dirty.js'

import type { CacheMixin }    from './cache-mixin.js'

/**
 * Explicit return type annotation truncates the TypeScript instantiation depth
 * for the callers (puppet-abstract.ts validateMixin chain) that otherwise trigger TS2589.
 */
type CallMixinReturn<MixinBase extends CacheMixin & typeof PuppetSkeleton> =
  MixinBase & (abstract new (...args: any[]) => {
    callInvite(contactIds: string[], media: CallMediaType): Promise<string>,
    callAdd(callId: string, contactIds: string[]): Promise<void>,
    callMediaEndpoint(callId: string): Promise<CallMediaEndpointPayload>,
    callAccept(callId: string): Promise<void>,
    callReject(callId: string, reason?: string): Promise<void>,
    callCancel(callId: string): Promise<void>,
    callHangup(callId: string, reason?: string): Promise<void>,
    callRawPayload(callId: string): Promise<any>,
    callRawPayloadParser(rawPayload: any): Promise<CallPayload>,
    callPayloadCache(callId: string): undefined | CallPayload,
    callPayload(callId: string): Promise<CallPayload>,
    callPayloadDirty(id: string): Promise<void>,
  })

const callMixin = <MixinBase extends CacheMixin & typeof PuppetSkeleton>(mixinBase: MixinBase): CallMixinReturn<MixinBase> => {

  abstract class CallMixin extends mixinBase {

    constructor (...args: any[]) {
      super(...args)
      log.verbose('PuppetCallMixin', 'constructor()')
    }

    /**
     * Initiate an outbound call to one or more contacts.
     *
     * A single-element array starts a 1v1 call; multiple elements start a
     * group call. Either way, one call mints exactly one callId, which is
     * generated by the puppet implementation (the protocol side), not by the
     * caller. The remote parties' responses — including events that may arrive
     * before this Promise resolves — are delivered uplink through the 'call'
     * event.
     *
     * Errors-only semantics: a resolved Promise carries the minted callId and
     * only means the protocol side has accepted the invite — it does NOT mean
     * any callee has answered. The callees' business responses (ringing /
     * accept / reject) are delivered uplink through the 'call' event.
     *
     * The `media` argument sets the call's INITIAL media type only. A later
     * voice<->video switch is observed via dirty(DirtyType.Call) → callPayload()
     * and does not produce a new invite.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callInvite (contactIds: string[], media: CallMediaType): Promise<string>

    /**
     * Add contacts to an existing call (callAdd is to callInvite what
     * roomAddV2 is to roomCreate).
     *
     * Errors-only semantics: a resolved Promise only means the add request
     * has been accepted by the protocol side. The new participants' business
     * responses (ringing / accept / reject) are delivered uplink through the
     * 'call' event — EventCallPayload.contactId is the new participant (the
     * actor of that signal); the updated roster is observed via
     * dirty(DirtyType.Call) → callPayload(). Add-specific failures (call not
     * found / already ended, participant cap exceeded) are expressed via
     * Promise rejection.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callAdd (callId: string, contactIds: string[]): Promise<void>

    /**
     * Pull the admission ticket of this call for the direct-to-gateway
     * media mode.
     *
     * The bot link only hands out this ticket: the holder (frontend / media
     * service) connects directly to the protocol side's media gateway with
     * it, and SDP/ICE negotiation plus media transport happen on that direct
     * channel — neither goes through the puppet contract.
     *
     * Pull on demand: typically called after callAccept(), when the media is
     * about to be attached — whoever consumes the media pulls its own ticket
     * (both sides symmetric, each on its own timing). The credential is
     * short-lived; once expired, call again to obtain a fresh ticket.
     * Issuing a ticket may pre-allocate a media session on the gateway, so
     * pure signaling consumers are never forced to trigger it.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callMediaEndpoint (callId: string): Promise<CallMediaEndpointPayload>

    /**
     * Accept an incoming call.
     *
     * Only meaningful for an incoming call. The protocol side locates the
     * call session by callId (from the incoming-call event).
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callAccept (callId: string): Promise<void>

    /**
     * Reject an incoming call.
     *
     * Only meaningful for an incoming call. The protocol side locates the
     * call session by callId (from the incoming-call event).
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callReject (callId: string, reason?: string): Promise<void>

    /**
     * Cancel an outbound call before it is connected.
     *
     * Only meaningful for an outbound call that has not been connected yet.
     * The protocol side locates the call session by callId (from callInvite()).
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callCancel (callId: string): Promise<void>

    /**
     * Hang up a connected call.
     *
     * Only meaningful for a call that is already connected. The protocol side
     * locates the call session by callId.
     *
     * Implementations that do not support call signaling should
     * `throw throwUnsupportedError()` (see other puppet implementations' convention).
     */
    abstract callHangup (callId: string, reason?: string): Promise<void>

    /**
     * @protected Issue #155 - https://github.com/wechaty/puppet/issues/155
     */
    abstract callRawPayload (callId: string): Promise<any>
    /**
     * @protected Issue #155 - https://github.com/wechaty/puppet/issues/155
     */
    abstract callRawPayloadParser (rawPayload: any): Promise<CallPayload>

    /**
     * Issue #155 - https://github.com/wechaty/puppet/issues/155
     *
     * @protected
     */
    callPayloadCache (callId: string): undefined | CallPayload {
      // log.silly('PuppetCallMixin', 'callPayloadCache(id=%s) @ %s', callId, this)
      if (!callId) {
        throw new Error('no id')
      }
      const cachedPayload = this.cache.call?.get(callId)

      if (cachedPayload) {
        // log.silly('PuppetCallMixin', 'callPayload(%s) cache HIT', callId)
      } else {
        log.silly('PuppetCallMixin', 'callPayload(%s) cache MISS', callId)
      }

      return cachedPayload
    }

    /**
     * Snapshot of the call session's current state (media, roster).
     * Kept fresh via the dirty mechanism: the protocol side emits
     * dirty(DirtyType.Call, callId) on any state change, which evicts the
     * cache here so the next pull fetches the updated payload.
     */
    async callPayload (
      callId: string,
    ): Promise<CallPayload> {
      // log.silly('PuppetCallMixin', 'callPayload(id=%s) @ %s', callId, this)

      if (!callId) {
        throw new Error('no id')
      }

      /**
       * 1. Try to get from cache first
       */
      const cachedPayload = this.callPayloadCache(callId)
      if (cachedPayload) {
        return cachedPayload
      }

      /**
       * 2. Cache not found
       */
      const rawPayload = await this.callRawPayload(callId)
      const payload    = await this.callRawPayloadParser(rawPayload)

      if (!this.cache.disabled) {
        this.cache.call?.set(callId, payload)
        log.silly('PuppetCallMixin', 'callPayload(%s) cache SET', callId)
      }

      return payload
    }

    async callPayloadDirty (
      id: string,
    ): Promise<void> {
      log.verbose('PuppetCallMixin', 'callPayloadDirty(%s)', id)

      await this.__dirtyPayloadAwait(
        DirtyType.Call,
        id,
      )
    }

  }

  return CallMixin as unknown as CallMixinReturn<MixinBase>
}

type CallMixin = ReturnType<typeof callMixin>
type ProtectedPropertyCallMixin =
  | 'callRawPayload'
  | 'callRawPayloadParser'
  | 'callPayloadCache'

export type {
  CallMixin,
  ProtectedPropertyCallMixin,
}
export { callMixin }
